version: '3.8'

services:
  sensus:
    image: ghcr.io/flaviosantti/sensus:latest
    container_name: sensus_app
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Favucanet"
        - "traefik.http.routers.sensus.rule=Host(`sensus.flaviosantiago.com.br`)"
        - "traefik.http.routers.sensus.entrypoints=websecure"
        - "traefik.http.routers.sensus.tls=true"
        - "traefik.http.routers.sensus.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.sensus-svc.loadbalancer.server.port=80"
    networks:
      - Favucanet

networks:
  Favucanet:
    external: true
